if($today == 'Monday') {
        echo "<img src='images/pumpkin-spice-latte.jpg' alt='Our Pumpkin Spice Latte tastes great on a Fall Day!' id='coffee' /><h3 class='feature1'>Monday's Coffee Special:</h3> <p><strong class='feature1'>Triple Shot Espresso.</strong> Monday morning--time to wake up! Gluten-free selfies normcore chillwave. Listicle 90's chambray, seitan cold-pressed try-hard Etsy authentic flexitarian vinyl. Meditation bespoke freegan, single-origin coffee cred seitan 90's gentrify brunch Williamsburg squid cold-pressed.</p>
        <p><span class='feature1'>Enjoy our Triple Shot Espresso</span> with a Polaroid iPhone plaid, Pitchfork Shoreditch paleo. Hashtag keytar chia scenester Pinterest, semiotics tousled food truck. YOLO scenester deep v, taxidermy paleo quinoa McSweeney's Carles VHS mustache Williamsburg gluten-free readymade cold-pressed. Truffaut Thundercats Schlitz, listicle organic Brooklyn paleo squid asymmetrical readymade migas gluten-free Austin.</p>";
   
    }elseif($today == 'Tuesday'){
        echo "<img src='images/pumpkin-spice-latte.jpg' alt='Our Pumpkin Spice Latte tastes great on a Fall Day!' id='coffee' /><h3 class='feature2'>Tuesday's Coffee Special:</h3> <p><strong class='feature2'>Tall Mocha.</strong> Tuesday morning's comfort coffee. Gluten-free selfies normcore chillwave. Listicle 90's chambray, seitan cold-pressed try-hard Etsy authentic flexitarian vinyl. Meditation bespoke freegan, single-origin coffee cred seitan 90's gentrify brunch Williamsburg squid cold-pressed.</p>
        <p><span class='feature2'>Enjoy our Tall Mocha </span>with a Polaroid iPhone plaid, Pitchfork Shoreditch paleo. Hashtag keytar chia scenester Pinterest, semiotics tousled food truck. YOLO scenester deep v, taxidermy paleo quinoa McSweeney's Carles VHS mustache Williamsburg gluten-free readymade cold-pressed. Truffaut Thundercats Schlitz, listicle organic Brooklyn paleo squid asymmetrical readymade migas gluten-free Austin.</p>";
    
     }elseif($today == 'Wednesday'){
        echo "<img src='images/pumpkin-spice-latte.jpg' alt='Our Pumpkin Spice Latte tastes great on a Fall Day!' id='coffee' /><h3 class='feature3'>Wednesday's Coffee Special:</h3> <p><strong class='feature3'>Tall Americano.</strong> Wednesday--halfway through the work week! Gluten-free selfies normcore chillwave. Listicle 90's chambray, seitan cold-pressed try-hard Etsy authentic flexitarian vinyl. Meditation bespoke freegan, single-origin coffee cred seitan 90's gentrify brunch Williamsburg squid cold-pressed.</p>
        <p><span class='feature3'>Enjoy our Tall Americano</span> with a Polaroid iPhone plaid, Pitchfork Shoreditch paleo. Hashtag keytar chia scenester Pinterest, semiotics tousled food truck. YOLO scenester deep v, taxidermy paleo quinoa McSweeney's Carles VHS mustache Williamsburg gluten-free readymade cold-pressed. Truffaut Thundercats Schlitz, listicle organic Brooklyn paleo squid asymmetrical readymade migas gluten-free Austin.</p>";
    
    }elseif($today == 'Thursday'){
        echo "<img src='images/pumpkin-spice-latte.jpg' alt='Our Pumpkin Spice Latte tastes great on a Fall Day!' id='coffee' /><h3 class='feature4'>Thursday's Coffee Special:</h3> <p><strong class='feature4'>Caramelized Honey Latte.</strong> Yum, and it's Thursday. Gluten-free selfies normcore chillwave. Listicle 90's chambray, seitan cold-pressed try-hard Etsy authentic flexitarian vinyl. Meditation bespoke freegan, single-origin coffee cred seitan 90's gentrify brunch Williamsburg squid cold-pressed.</p>
        <p><span class='feature4'>Enjoy our Caramelized Honey Latte</span> with a Polaroid iPhone plaid, Pitchfork Shoreditch paleo. Hashtag keytar chia scenester Pinterest, semiotics tousled food truck. YOLO scenester deep v, taxidermy paleo quinoa McSweeney's Carles VHS mustache Williamsburg gluten-free readymade cold-pressed. Truffaut Thundercats Schlitz, listicle organic Brooklyn paleo squid asymmetrical readymade migas gluten-free Austin.</p>";
    
    }elseif($today == 'Friday'){
        echo "<img src='images/pumpkin-spice-latte.jpg' alt='Our Pumpkin Spice Latte tastes great on a Fall Day!' id='coffee' /><h3 class='feature5'>Friday's Coffee Special:</h3> <p><strong class='feature5'>Pumpkin Spice Latte.</strong>  Hallelujah--it's Friday! Gluten-free selfies normcore chillwave. Listicle 90's chambray, seitan cold-pressed try-hard Etsy authentic flexitarian vinyl. Meditation bespoke freegan, single-origin coffee cred seitan 90's gentrify brunch Williamsburg squid cold-pressed.</p>
        <p><span class='feature5'>Pumpkin Spice Latte</span> with a Polaroid iPhone plaid, Pitchfork Shoreditch paleo. Hashtag keytar chia scenester Pinterest, semiotics tousled food truck. YOLO scenester deep v, taxidermy paleo quinoa McSweeney's Carles VHS mustache Williamsburg gluten-free readymade cold-pressed. Truffaut Thundercats Schlitz, listicle organic Brooklyn paleo squid asymmetrical readymade migas gluten-free Austin.</p>";
    
    }elseif($today == 'Saturday'){
        echo "<img src='images/pumpkin-spice-latte.jpg' alt='Our Pumpkin Spice Latte tastes great on a Fall Day!' id='coffee' /><h3 class='feature6'>Saturday's Coffee Special:</h3> <p><strong class='feature6'>Cinnamon Dolce Latte.</strong> It's Saturday, and life is good. Gluten-free selfies normcore chillwave. Listicle 90's chambray, seitan cold-pressed try-hard Etsy authentic flexitarian vinyl. Meditation bespoke freegan, single-origin coffee cred seitan 90's gentrify brunch Williamsburg squid cold-pressed.</p>
        <p><span class='feature6'>Enjoy our Cinnamon Dolce Latte</span> with a Polaroid iPhone plaid, Pitchfork Shoreditch paleo. Hashtag keytar chia scenester Pinterest, semiotics tousled food truck. YOLO scenester deep v, taxidermy paleo quinoa McSweeney's Carles VHS mustache Williamsburg gluten-free readymade cold-pressed. Truffaut Thundercats Schlitz, listicle organic Brooklyn paleo squid asymmetrical readymade migas gluten-free Austin.</p>";
    }else{
        echo "<img src='images/pumpkin-spice-latte.jpg' alt='Our Pumpkin Spice Latte tastes great on a Fall Day!' id='coffee' /><h3 class='feature7'>Sunday's Coffee Special:</h3> <p><strong class='feature7'>Espresso Con Panna</strong> Sunday--relax and enjoy. Gluten-free selfies normcore chillwave. Listicle 90's chambray, seitan cold-pressed try-hard Etsy authentic flexitarian vinyl. Meditation bespoke freegan, single-origin coffee cred seitan 90's gentrify brunch Williamsburg squid cold-pressed.</p>
        <p><span class='feature7'>Enjoy our Espresso Con Panna</span> with a Polaroid iPhone plaid, Pitchfork Shoreditch paleo. Hashtag keytar chia scenester Pinterest, semiotics tousled food truck. YOLO scenester deep v, taxidermy paleo quinoa McSweeney's Carles VHS mustache Williamsburg gluten-free readymade cold-pressed. Truffaut Thundercats Schlitz, listicle organic Brooklyn paleo squid asymmetrical readymade migas gluten-free Austin.</p>";
    }
